# Generated by Django 3.0.3 on 2020-06-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('teacher_no', models.IntegerField()),
                ('teacher_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
